from ast import Return
from distutils.log import debug
from flask import Flask,render_template,request
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer, ChatterBotCorpusTrainer
from chatterbot.response_selection import get_random_response

app = Flask(__name__)

# Create object of ChatBot class
bot = ChatBot(
    "chatbot",
    response_selection_method=get_random_response,
    read_only= False,
    logic_adapters =[
        {
            "import_path":"chatterbot.logic.BestMatch",
            "default_response":"Sorry i dont have an answer",
            "maximum_similarity_threshold": 0.8
        }
    ]
)

list_to_train2 = [
                "hey",
                "hey there",
                "what\'s your name ?",
                "i\'m a chatbot",
                "how old are you ?",
                "im ageless",
                "why are you so mad ?",
                "i'm not",
                "this is good right ?",
                "yeah dude",
                "do you have iphone ?",
                "i've everything!",
                "what's your favorite food ?",
                "data",
                "what's your job?",
                "I'm here to answer your questions",
                "I don't know what you're talking about",
                "hey",
                "hey mate",
                "what\'s your name ?",
                "i\'m your assistant",
                "how old are you ?",
                "im olds",
                "why are you so mad ?",
                "because of you",
                "this is good right ?",
                "yeah dude",
                "do you have iphone ?",
                "of course i do",
                "what's your favorite food ?",
                "i dont eat",
                "what's your job?",
                "I'm an assistant",
                "I don't know what you're talking about",
                "When should I arrive?",
                "you should arrive at 9:00 in the morning",
                "Where do I go when I arrive?",
                "you should go to the appointed desktop contact the human ressources for further information 0666999999",
                "Do I need a buzzer or key to get into the building?",
                "No you dont need it the security opens and closes the building",
                "Is someone expecting me?",
                "yes your team leader will be expecting you",
                "Who do I call if I’m running late?",
                "contact the team leader at 0696669999 or the human ressources at 0699988888",
                "Is there on-site parking?",
                "yes there is an area close to the building where you can park",
                "What should I wear?",
                "Any thing you want just Make sure that they aren't too revealing.",
                "What do I need with me?",
                "you need your card id to enter the building",
                "What will my first day involve",
                "an introduction to the company and an explanation of ur tasks",
                "Should I bring lunch or do people eat out?",
                "there is a restaurant close to the building but you could bring lunch",
                "When and how do I get paid?",
                "at the end of each month via your account",
                "What expenses am I allowed and how do I claim?",
                "Parking, Business related and entertainment expenses,Business related and entertainment expenses",
                "What benefits do I get?",
                "you get to have those benefits Health insurance , Paid time off (PTO) such as sick days and vacation days , Flexible and remote working options , Life insurance.",
                "How does holiday work?",
                "you get a day and a half for each month",
                "How much notice should I give to book holiday?",
                "one week",
                "What\’s the process if I\’m sick?",
                "you should send the medicale certificate under 48 hours",
                "Can I work from home occasionally?",
                "Yes but check with your team leader first",
                "yes,and yes",
                "Will I get in trouble if I answer personal emails or calls?",
                "no you wont",
                "How do I connect to the internet and intranet?",
                "we sent you an email with detailed informations",
                "What\’s my email address?",
                "your email is firstnamelastname@pre-history.ma",
                "Where can I find colleagues email addresses?",
                "you can find them in your email box",
                "Should I use a company email signature?",
                "yes for contacting colleagues and other teams",
                "What should I write on my LinkedIn profile?",
                "discuss this with the human ressource",
                "Am I allowed to talk about work on social media?",
                "you cant share sensible data but you can talk about your experience in social media",
                "How long do I get for breaks and lunch?",
                "an hour for lunch and 30 minutes for break",
                "Can I eat whenever I want?",
                "yes",
                "Can I eat at my desk?",
                "preferably no u can eat in the cafeteria",
                "Can I leave the office to eat?",
                "yes just lock ur account",
                "What in the kitchen is for sharing?",
                "coffee and Milk",
                "Why does this company exist?",
                "this company exist to solve real life challenges in the IT ",
                "What are the company\’s goals?",
                "to grow and get better reputation",
                "What are the company\’s challenges?",
                "Competencies and recruiting the right talent , Technology , Exploding data",
                "How does my job relate to those goals?",
                "we recruited you to help us achieve those goals",
                "Why does my job matter?",
                "because you are a problem solver and while you work, you're gaining self-worth and self-dignity",
                "How much on-the-job training is there?",
                "two months",
                "What are my performance goals for the month/quarter/year?",
                "you should ask your team leader at 0698668686 or via email teamleader@pre-history.ma",
                "How is performance measured?",
                "by the tickets you solve ",
                "Who do I most need to impress?",
                "your team leader",
                "Do most employees meet all their goals?",
                "sometime they do sometime they dont",
                "What standard are other new hires?",
                "candidates who are enthusiastic and passionate about what they do",
                "What happens if I don’t meet my performance goals?",
                "it depends in the effort u put ",
                "Where can I get help, if I’m struggling?",
                "your team leader or colleagues",
                "Can I be involved in setting performance goals?",
                "no the team leader decide but u can discuss with him",
                "What would exceptional performance look like?",
                "solving many tickets or adapting to a new technology fast",
                "What happens if I achieve exceptional performance?",
                "you will get a bonus and scale up fast in the company with time",
                "Are there any unspoken objectives here?",
                "no but we like clean code",
                "How can I go above and beyond? ",
                "practice and persistance",
                "Who can I ask if I have questions about my job or the company?",
                "your team leader or manager or human ressources",
                "Who can I talk to if I have a problem or something bad has happened?",
                "your team leader or manager or human ressources",
                "Who can I talk to if I have a cool idea outside my formal job remit? ",
                "you should reach the manager or human ressource",
                "Are there people like me here?",
                "yeah i am sure you will fit in",
                "Are people open and welcoming?",
                "yes our team is top notch in manners",
                "Will people understand if I\’m socially anxious?",
                "yes we have a culture of love",
                "When will I meet people?",
                "whenever you come to the office",
                "Do people socialise together?",
                "yes and we have group activities",
                "If so, when and how?",
                "during breaks and lunch",
                "How can I integrate socially?",
                "just try to open up and be kind to others",
                "Can I meet my team before we start?",
                "we can arrange that please contact human ressource or your team leader",
                "How will I remember everyone’s name? ",
                "right them down and use them whenever you can",
                "What are people like?",
                "kind and open",
                "What\’s the office like?",
                "a classy office i guess",
                "Which office lingo do people use?",
                "80/20",
                "What time do people really arrive?",
                "9.00 but we can tolerate a 20 minute late",
                "What time do people really leave?",
                "6.00",
                "Will I be judged if I leave on-time?",
                "yes",
                "Am I expected to answer emails out-of-hours?",
                "yes",
                "What are the unspoken no-no\’s?",
                "there is none just dont be hateful",
                "Does my boss/the department head/the CEO have any pet hates?",
                "i dont know but we dont allow pets inside",
                "Do we celebrate birthdays?",
                "it depends on your team",
                "Do we have a Christmas party?",
                "no we dont",
                "How should I behave to fit in? ",
                "the way you normally do",
                "How do I get promoted?",
                "hard work and recommandation",
                "Is there a minimum time-frame for promotion?",
                "talk with the human ressources",
                "What potential hurdles to promotion are there?",
                "slacking and being unproductive",
                "What extra responsibilities can I take on?",
                "you can ask your team leader",
                "Will you pay for external training, like an MA or course?",
                "yeah we have scholarships in some universities",
                "How much training can I expect and when?",
                "at the beginning for two month and there might be more",
                "Can I request extra training?",
                "yes talk to the human ressources for more informations",
                "Will I get experience in different areas if I want it?",
                "yes but its better to specialize",
                "What projects will I work on?",
                "projects with impact on real life",
                "What could my career look like in a year/two years/five years?",
                "you will advance in the company talk with the human ressources for more informations",
                "What technologies do use here?",
                "Our technical stuff differs from team to team, let me share with you some of them: Java, Spring, C#, .NET, Javascript, React, Angular and more",
                ".Net",
                "For our team formation, follow this course and you will learn all the needed information about .Net: https://www.pluralsight.com/paths/net-framework-class-libraries-with-cwe",
                "Angular",
                "For our team formation, follow this course and you will learn all the needed information about Angular: https://www.pluralsight.com/paths/angular",			
                "ASP.NET core",
                "For our team formation, follow this course and you will learn all the needed information about ASP.NET core: https://www.pluralsight.com/paths/aspnet-core",
                "ASP.NET",
                "For our team formation, follow this course and you will learn all the needed information about ASP.NET core: https://www.pluralsight.com/paths/aspnet-core",
                "React Native",
                "For our team formation, follow this course and you will learn all the needed information about : https://www.pluralsight.com/paths/build-mobile-applications-with-react-native",
                "Dev mobile",
                "For our team formation, follow this course and you will learn all the needed information about : https://www.pluralsight.com/paths/build-mobile-applications-with-react-native",
                "React",
                "For our team formation, follow this course and you will learn all the needed information about : https://www.pluralsight.com/paths/building-web-applications-with-react",
                "Vue js",
                "For our team formation, follow this course and you will learn all the needed information about : https://www.pluralsight.com/paths/building-web-apps-with-vue",
                "HTML",
                "For our team formation, follow this course and you will learn all the needed information about : https://www.pluralsight.com/paths/building-websites-with-html-css-and-javascript",
                "CSS",
                "For our team formation, follow this course and you will learn all the needed information about : https://www.pluralsight.com/paths/building-websites-with-html-css-and-javascript",
                "Javascript",
                "For our team formation, follow this course and you will learn all the needed information about : https://www.pluralsight.com/paths/building-websites-with-html-css-and-javascript",
                "Python",
                "For our team formation, follow this course and you will learn all the needed information about :https://www.pluralsight.com/paths/core-python",
                "Android",
                "For our team formation, follow this course and you will learn all the needed information about : https://www.pluralsight.com/paths/android-development-with-kotlin-fundamentals",
                "Kotlin",
                "For our team formation, follow this course and you will learn all the needed information about : https://www.pluralsight.com/paths/android-development-with-kotlin-fundamentals",
                "Git",
                "For our team formation, follow this course and you will learn all the needed information about : https://www.pluralsight.com/paths/managing-source-code-with-git",
                "PHP",
                "For our team formation, follow this course and you will learn all the needed information about : https://www.pluralsight.com/paths/php-development-fundamentals",
                "Spring",
                "For our team formation, follow this course and you will learn all the needed information about : https://www.pluralsight.com/paths/spring-framework-core-spring",
                "JQuery",
                "For our team formation, follow this course and you will learn all the needed information about : https://www.pluralsight.com/paths/building-dynamic-websites-with-jquery",
                "Go",
                "For our team formation, follow this course and you will learn all the needed information about : https://www.pluralsight.com/paths/go-core-language"

]
#Training our data
list_trainer = ListTrainer(bot)
list_trainer.train(list_to_train2)


#to include chatterbot-corpus training remove the dash
#trainer = ChatterBotCorpusTrainer(bot)
#trainer.train("chatterbot.corpus.english")


@app.route("/")
def main():
    return render_template("index.html") 

@app.route("/get")
def get_chatbot_response():
    userText = request.args.get('userMessage')
    return str(bot.get_response(userText))

if __name__ == "__main__":
    app.run(debug=True)